### ISSUE TITLE
BigInt support.

### ISSUE THREAD

**Issue by skyf0l** [elmomoilanen/prime-factorization#2]
Factoring u128 is fine, but this tool could be more useful if it could factor BigInt quickly.
(See `rug::Integer` for fast BigInt crate.)

**Comment by elmomoilanen** [comment]
Thanks for the comment.

You're correct that being able to factor arbitrary large integers would be very useful.

I will consider what you suggest but certainly I need to evaluate how much effort this update would require and when I could have enough time for it.

**Comment by elmomoilanen** [comment]
I have decided to continue supporting factorization only for integers up to 128 bits.
